# Generated by Django 2.2.7 on 2020-01-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('link_id', models.CharField(max_length=100)),
            ],
        ),
    ]
